---
- name: Изменение системного приветствия (motd)
  hosts: servers
  become: yes
  vars:
    custom_motd: "Once you log in, you'll have a lot of fun!!! Current time: {{ ansible_date_time.time }}"

  tasks:
    - name: Создать кастомное приветствие
      copy:
        content: |
          {{ custom_motd }}
          Сервер: {{ ansible_hostname }}
          ОС: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Ядро: {{ ansible_kernel }}
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'

    - name: Отключить динамическое обновление motd (если используется)
      file:
        path: /etc/update-motd.d
        state: absent
      when: ansible_os_family == "Debian"

    - name: Проверить изменение motd
      command: cat /etc/motd
      register: motd_content

    - name: Показать содержимое motd
      debug:
        msg: "Текущее приветствие: {{ motd_content.stdout }}"
